chroma_db:
  collection_name: "assignment2"

embedding_model:
  provider: "huggingface"
  model_name: "all-MiniLM-L6-v2"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "gemma2-9b-it" 